name: bottles
version: git
adopt-info: bottles
base: core20
confinement: strict
grade: stable
license: GPL-3.0+
icon: data/icons/hicolor/scalable/apps/com.usebottles.bottles.svg

architectures:
  - build-on: [amd64]
    
parts:

  bottles:
    after: [enable-i386]
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    source: https://github.com/bottlesdevs/Bottles.git
    parse-info: [usr/share/metainfo/com.usebottles.bottles.appdata.xml]
    override-pull: |
      snapcraftctl pull
      sed -i -e 's|@PYTHON@|/usr/bin/python3|g' src/bottles.in
      sed -i.bak -e 's|Icon=com.usebottles.bottles|Icon=/usr/share/icons/hicolor/scalable/apps/com.usebottles.bottles.svg|g' data/com.usebottles.bottles.desktop.in
    build-packages:
      - python3
      - python3-distutils
      - python3-pytoml
      - python3-requests
      - libnotify-dev
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - python3-markdown
      - libnotify4
      - gamemode
      - libgamemode0
      - winbind
      - libfreetype6
      - cabextract
      - wine
      - p7zip
      - p7zip-full
      - patool
      - on amd64:
          - libc6-i386
          - libglx-mesa0:i386
          - libgnutls30:i386
          - libvulkan1:i386
          - libfreetype6:i386
    organize:
      snap/bottles/current/usr: usr
    prime:
      - -usr/lib/*/*pango*
      - -usr/lib/*/*cairo*
      - -usr/lib/*/libgtk*
      - -usr/lib/*/libgdk*
      - -usr/lib/*/librsvg*
      - -usr/lib/girepository-1.0
  
  enable-i386:
    plugin: nil
    override-build: |
      snapcraftctl build
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        dpkg --add-architecture i386
        apt update
      fi

  fix-p7zip:
    plugin: nil
    after: [ bottles ]
    override-prime: |
      snapcraftctl prime
      sed -i -e 's|/usr/lib/p7zip/7z|/snap/bottles/current/usr/lib/p7zip/7z|g' usr/bin/7z

apps:
  bottles:
    command: usr/bin/bottles
    desktop: usr/share/applications/com.usebottles.bottles.desktop
    common-id: com.usebottles.bottles.desktop
    extensions: [gnome-3-38]
    environment:
        PYTHONPATH: ${PYTHONPATH}:$SNAP/usr/lib/python3/dist-packages
    plugs:
      - home
      - gsettings
      - network
      - audio-playback
      - audio-record
      - removable-media
    slots:
      - dbus-bottles

slots:
  dbus-bottles:
    interface: dbus
    bus: session
    name: com.usebottles.bottles
